### ISSUE TITLE
lldb build failed  OSX 10.11

### ISSUE THREAD

**Issue by rogermc2** [meeloo/xspray#8]
Following you excellent instructions, all went well until I tried to build LLDB which failed with one fatal error:
llvm/Config/llvm-config.h file not found.
This file is required by lldb/llvm/include/llvm/Support/Compiler.h  at line 18.
Obviously (?) not an xspray problem but an lldb configuration problem.
Can someone suggest a way of overcoming this problem?

**Comment by meeloo** [comment]
Maybe they changed something in the lldb configuration since the last time I tried to build this project. Is there a configure or cmake script in the lldb repos? Try to see if they have updates build instructions on the website also?

**Comment by rogermc2** [comment]
I found your advice "checkout a fresh LLDB to replace the current broken one" to be essential!
However, once I got lldb running, the Xspray OSX build failed with:
pmenergy.h not found.
I also discovered that 
pmsample.h not found.
These files are required by MachTask.mm which seems to be an lldb debugserver file.
Hence an lldb problem?
These files are only required if LLDB_ENERGY is defined.
As I couldn't find where LLDB_ENERGY is defined, I undefined LLDB_ENERGY in  MachTask.mm which allowed the build to continue.
Presumably, I should undefine it elsewhere?

**Comment by rogermc2** [comment]
Next problem nui3 build failed by not finding QTKit files.
I couldn't figure out why. It seems OSX wouldn't allow it! Everything that I checked, including permissions, seemed OK.
Maybe something to do with QTKit being deprecated in favour of another framework.
Solved by copying QTKit directory into nui3/include.
nui3 build then succeeded.

**Comment by rogermc2** [comment]
I give up! Quite a pity as Xspray seems to be quite an interesting product.
A major problem seems to be that, when attempting to build Xspray OSX, the  Xspray OSX initiates a rebuild of lldb-core.
This rebuild fails due to its include folder not containing many required files that are, in fact, available in previous build products.
It seems strange that a "stand-alone" build of lldb-core succeeds whereas when initiated by the   Xspray OSX fails.
Is it necessary for Xspray OSX to initiate a rebuild of lldb-core. If not, can it be skipped in the Xspray OSX build process? If so, how?
